TeachersHelpTeachersDOxy: db_execute.Questions Class Reference
db_execute.Questions Class Reference
Public Member Functions
def get_categories ()
Static Public Member Functions
def get_from_category (category)
def get_from_author (author)
def get_from_both (author, category)
def create (author, category, question)
Detailed Description
This class contains calls to the questions table in the database.
Member Function Documentation
create()
def db_execute.Questions.create (author, category, question) static
This static method creates a new row in the databse for all of the question
attributes including the author's email, category, and question in its
raw form.
@param string author email
@param string category
@param string question
References db.get_db().
get_categories()
def db_execute.Questions.get_categories ()
This static method creates a list of all the categories in the database.
@return list of string categories
References db.get_db().
get_from_author()
def db_execute.Questions.get_from_author (author) static
This static method searches the databse for the author provided in the
paramter. It then returns the question attribute for the author.
@param string author email
@return string question
References db.get_db().
get_from_both()
def db_execute.Questions.get_from_both (author, category) static
This static method searches the databse for rows that contain both the
author and the category provided by the paramters. It then returns the
question attribute that matches the search.
@param string author email
@param string category
@return string question
References db.get_db().
get_from_category()
def db_execute.Questions.get_from_category (category) static
This static method searches the database for the category provided in the
parameter. It then returns the question attribute for the category.
@param string category
@return string question
References db.get_db().
The documentation for this class was generated from the following file:
C:/Users/Michelle/Documents/UNO_Software_Engineering/teachershelpteachers/db_execute.py