TeachersHelpTeachersDOxy: db Namespace Reference
db Namespace Reference
Functions
def get_db ()
def close_db (e=None)
def init_db ()
def init_db_command ()
def init_app (app)
Function Documentation
close_db()
def db.close_db (e = None)
get_db()
def db.get_db ()
Referenced by db_execute.Questions.create(), db_execute.User.create(), db_execute.User.get(), db_execute.Questions.get_categories(), db_execute.Questions.get_from_author(), db_execute.Questions.get_from_both(), db_execute.Questions.get_from_category(), init_db(), test_component.TestComponent.tearDown(), test_unit.TestUnit.tearDown(), and test_unit.TestUnit.test_questions_create().
init_app()
def db.init_app (app)
init_db()
def db.init_db ()
References get_db().
Referenced by init_db_command().
init_db_command()
def db.init_db_command ()
Clear the existing data and create new tables.
References init_db().